In [32]:
%%time
import sys
sys.path.insert(0, '/Users/kuangzheng/Programming/refactoring/codes/')

import os
import json
import warnings
import pprint


%reload_ext autoreload
%autoreload
%autoreload 2
%config Completer.use_jedi = False

CPU times: user 22.3 ms, sys: 16.9 ms, total: 39.1 ms
Wall time: 39.5 ms


In [36]:
import numpy as np
import scipy.io
from numpy.random import choice, laplace
from scipy.special import lambertw
from scipy.stats import laplace
from codes.kse_test import kse_test


In [77]:
C

array([60000,   495,  1976,  1610,   230,  3365,   825,   731,  1567,
         651,  1048,   588,   726,   729,   749,  1110,   694,   532,
         995,   229,  1528,   730,   469,   737,   619,   350,   521,
         238,   493,   348,   554,   272,   313,   173,   217,   231,
         881,    71,   156,   174,   271,    78,   168,    83,    83,
         161,    80,    80,    79,    64,   722,    19,    20,    10,
           6,    21,    10,     8,    11,     6,    16,    11,     9,
           7,     7,     3,     3,     3,     4,     1,     8,     6,
           3,     2,     2,     4,     1,     0,     2,     0,     2,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           1])

In [82]:
dataset4 = scipy.io.loadmat('4.mat')['dataset4']
sizeofD = 100
dataset2 = dataset4[:, :3]
S, _ = np.histogram(dataset2, bins=sizeofD)
eps = np.linspace(0.1, 2, 4)
B = S.reshape(-1, 1)
C = B[:sizeofD]
Output = kse_test(C)

pp = 1. / (Output ** 5)
pp = pp.reshape(-1)
pp /= pp.sum()
NN = 2 ** (15 * Output)
px = np.arange(1, sizeofD+1)

gamma = 0.5
rho = np.exp(lambertw(-gamma / (2 * np.exp(0.5)), k=-1) + 0.5)
rho = np.real(rho)
m = np.log(1 / rho) / (2 * (gamma - rho) ** 2)
k = m * (1 - gamma + rho + np.sqrt(np.log(1 / rho) / (2 * m)))
m = int(float(np.ceil(m)))
k = int(float(np.ceil(k)))


(100, 1)


In [83]:
noiseunif = kse_test(unif)

In [85]:
EVAL = np.zeros((4, 7))
EVAL1 = np.zeros((4, 7))

for rr in range(4):
    for j in range(1):
        C = B[:sizeofD].reshape(-1)
        GS = np.sort(np.random.choice(C, size=m, replace=False))
        Sensunif = GS[k-1]
        SS = np.sort(np.random.choice(px, size=m, replace=True, p=pp))
        SS = NN[np.floor(SS).astype(int)]
        SS = np.sort(SS)
        Sensanom = SS[k-1]

        unif = laplace.rvs(loc=0, scale=Sensunif/(eps[rr]), size=sizeofD) + C
        noiseanom = laplace.rvs(loc=0, scale=Sensanom/(eps[rr]), size=sizeofD) + NN

        noiseunif = kse_test(unif)
        noiseanom = kse_test(noiseanom)

        Index = np.zeros((sizeofD, 2))
        Index[:, 0] = np.arange(1, sizeofD+1)

        for i in range(sizeofD):
            if Output[i] > 0.7:
                Index[i, 1] = 1

        ACTUAL = Index
        Origindex = np.where(ACTUAL[:, 1] == 1)[0]

        Index = np.zeros((sizeofD, 2))
        Index[:, 0] = np.arange(1, sizeofD+1)

        for i in range(sizeofD):
            if noiseunif[i] > 0.7:
                Index[i, 1] = 1

        Uniformm = Index
        Pertindex = np.where(Uniformm[:, 1] == 1)[0]

        Index = np.zeros((sizeofD, 2))
        Index[:, 0] = np.arange(1, sizeofD+1)

        for i in range(sizeofD):
            if noiseanom[i] > 0.7:
                Index[i, 1] = 1

        Anomm = Index
        Pertindex1 = np.where(Anomm[:, 1] == 1)[0]
        IND1 = Anomm
        IND = Uniformm

        C = len(set(Origindex) | set(Pertindex))
        p = len(Origindex)
        n = sizeofD - p
        N = p + n
        tp = sum(ACTUAL[Origindex, 1] == IND[Origindex, 1])
        tn = N - C
        fp = n - tn
        fn = p - tp
        tp_rate = tp / p
        tn_rate = tn / n
        accuracy = (tp + tn) / N
        sensitivity = tp_rate
        specificity = tn_rate
        precision = tp / (tp + fp)
        recall = sensitivity
        f_measure = 2 * ((precision * recall) / (precision + recall))
        gmean = np.sqrt(tp_rate * tn)
        EVAL1[rr, :] += np.array([accuracy, tp, specificity, precision, recall, f_measure, gmean])
    EVAL[rr, :] = EVAL[rr, :] / j
    EVAL1[rr, :] = EVAL1[rr, :] / j



ZeroDivisionError: division by zero

In [89]:
Output

array([1.05263158e-02, 1.06046306e-02, 1.05263158e-02, 1.05263158e-02,
       1.14631775e-02, 1.05263158e-02, 1.05263158e-02, 1.18433935e-02,
       1.05263158e-02, 1.05263160e-02, 1.05263158e-02, 1.05263159e-02,
       1.05373582e-02, 1.11213761e-02, 1.05263159e-02, 1.05263158e-02,
       8.26606243e-11, 1.05263161e-02, 1.05263158e-02, 1.09141995e-02,
       1.05263158e-02, 1.14646509e-02, 1.05263158e-02, 1.05267425e-02,
       1.05263158e-02, 1.06046306e-02, 1.05263165e-02, 2.08408652e-07,
       1.05263158e-02, 1.07264663e-02, 1.05263158e-02, 1.05263164e-02,
       1.05263159e-02, 1.08360666e-02, 1.05263165e-02, 1.06048187e-02,
       1.05263158e-02, 1.05265775e-02, 1.05270624e-02, 1.05270624e-02,
       1.08358815e-02, 1.24784310e-02, 1.05271521e-02, 2.11122400e-02,
       2.11539684e-02, 1.05272658e-02, 2.20411764e-02, 2.14730943e-02,
       1.19371341e-02, 1.05264177e-02, 1.05291678e-02, 1.09242617e-02,
       1.11463703e-02, 3.07548338e-02, 6.24012233e-02, 1.12003129e-02,
      

In [71]:
noiseunif

array([1.])